FROM node:alpine3.21 AS build
LABEL maintainer="anusu90@gmail.com"
WORKDIR /product
COPY ./product/package*.json ./
RUN npm install
COPY ./product .
RUN npm run build



FROM nginx:1.29.3 AS production
COPY --from=build /product/dist /usr/share/nginx/html
COPY ./product/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]